### ISSUE TITLE
Consider including binaries for MacOS arm64 and/or Homebrew support?

### ISSUE THREAD

**Issue by evandam** [bluebrown/go-template-cli#12]
First I just wanted to say thanks for this project, it's really useful!

I was wondering what your thoughts would be around providing pre-compiled binaries for more platforms, ideally MacOS arm64 🤞 

It would also be super nice if it was possible to `brew install go-template-cli`. Thanks again!

**Comment by bluebrown** [comment]
hi @evandam, I wouldn't mind that.  Actually, I just refactored the architecture of the program recently. The changes are already in main but not released. It's not releasable yet because now there isn't any logic to build the stuff and attach it to the GitHub release.

If you want, you can make a pr and add that functionality and attach binaries for linux, mac and maybe windows.

I have setup release-please https://github.com/bluebrown/go-template-cli/blob/main/.github/workflows/release-please.yaml, so you could hook into the github release creation and build / attach the artifacts, if possible. 

I know there is also goreleaser which can do all the heavy lifting. Though, I am not sure if it could be integrated with release-please. But I am also not super fixated on release-please.

So all in all this is a greenfield. I would be happy with whatever you come up, as long as its based on conventional commits.

Otherwise, I might get around these days to create a release flow myself.

Cheers

**Comment by bluebrown** [comment]
i have changed the release flow to include the mac binaries. https://github.com/bluebrown/go-template-cli/releases/tag/v0.3.0
